---
spring:
  profiles: default
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
server:
  port: 8081
brian:
  mq:
    protocol: http
    port: 15672
---
spring:
  profiles: development
  rabbitmq:
    host:
    port: 5672
    username:
    password:
brian:
  mq:
    protocol: https
    port: 80